#!/bin/bash
# james.a.munsch@gmail.com 2014 Copyleft
# use it how you want
# A simple speech to text for googles tts
# using bash
# usage: speakit filename

INSTALLED=$(dpkg-query -l "mpg123")

if [[ $? == 1 ]]; then
    exit
fi

if [[ ! $1 ]]; then
    cat - <<EOF
usage: 
    bash_speakit /path/to/file.txt
EOF
    exit
fi

LINE=$(cat $1 | tr '\n' ' ')
count=0
TMPARRAY=()
word=

speakit () {
    echo "${TMPARRAY[@]}"
    echo $1
    if $1; then

        :
    else
        prevword=${TMPARRAY[${#TMPARRAY[@]}-1])} # store previous word
        echo PREVIOUSWORD
        echo $prevword
        unset TMPARRAY[$((${#TMPARRAY[@]} - 1 ))]
    fi
    results=$(join + "${TMPARRAY[@]}")
    # remove url unsafe characters
    results=$(sed -e 's:%::g' \
-e 's: ::g' \
-e 's:<::g' \
-e 's:>::g' \
-e 's:#::g' \
-e 's:{::g' \
-e 's:}::g' \
-e 's:|::g' \
-e 's:\\::g' \
-e 's:\^::g' \
-e 's:~::g' \
-e 's:\[::g' \
-e 's:\]::g' \
-e 's:`::g' \
-e 's:;::g' \
-e 's:/::g' \
-e 's:?::g' \
-e 's^:^^g' \
-e 's:@::g' \
-e 's:=::g' \
-e 's:&::g' \
-e 's:\$::g' \
-e 's:\!::g' \
-e 's:\*::g' <<< $results)
    echo ${#results}
    # language can be set by replace 'tl=en' with 'tl=LANGUAGE'
    wget -q -U Mozilla -O output.mp3 "http://translate.google.com/translate_tts?ie=UTF-8&tl=en&q=$results" && mpg123 output.mp3
    TMPARRAY=("$prevword")
    echo "${TMPARRAY[@]}"
    count=$((${#prevword} + 1))
}

join () { 
    local IFS="$1";shift; echo "$*";
}

lastcount=0
words=0
for word in $LINE; do
    words=$(( $words + 1))
done
for word in $LINE; do
    lastcount=$(( $lastcount + 1 ))
    if (( $(( $count + ${#word} )) < 100 )); then
        TMPARRAY+=("$word")
        count=$(( $count + ${#word} + 1))
        if (( $lastcount == $words )); then
            speakit true
        fi
    else
        TMPARRAY+=("$word")
        speakit false
    fi
done
